<?php
// +----------------------------------------------------------------------
// |ZBPHP[基于ThinkPHP5.1开发]
// +----------------------------------------------------------------------
// | Copyright (c) 2016-2019 http://www.benbenwangluo.com
// +----------------------------------------------------------------------
// | Author 似水星辰 [ 2630481389@qq.com ]
// +----------------------------------------------------------------------
// | 中犇软件 技术六部 出品
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
  [
    'title' => '运营',
    'icon' => 'fa fa-fw  fa-briefcase',
    'url_value' => 'operation/ads/index',
    'url_target' => '_self',
    'online_hide' => 0,
    'sort' => 6,
    'status' => 1,
    'child' => [
      [
        'title' => '文章管理',
        'icon' => 'fa fa-fw fa-file-word-o',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 99,
        'status' => 1,
        'child' => [
          [
            'title' => '文章列表',
            'icon' => 'fa fa-fw fa-list-ul',
            'url_value' => 'operation/article/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 99,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'operation/article/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'operation/article/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'operation/article/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '设置状态',
                'icon' => '',
                'url_value' => 'operation/article/setstatus',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '文章分类',
            'icon' => 'fa fa-fw fa-list-ul',
            'url_value' => 'operation/article_column/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 99,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'operation/article_column/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'operation/article_column/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'operation/article_column/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '设置状态',
                'icon' => '',
                'url_value' => 'operation/article_column/setstatus',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '消息推送',
        'icon' => 'fa fa-fw fa-twitch',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 99,
        'status' => 1,
        'child' => [
          [
            'title' => '消息推送',
            'icon' => 'fa fa-fw fa-hand-pointer-o',
            'url_value' => 'operation/message_push/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 99,
            'status' => 1,
            'child' => [
              [
                'title' => '重发',
                'icon' => '',
                'url_value' => 'operation/message_push/send',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 99,
                'status' => 1,
              ],
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'operation/message_push/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '站内信件',
            'icon' => 'fa fa-fw fa-envelope-o',
            'url_value' => 'operation/system_message/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 99,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'operation/system_message/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'operation/system_message/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '广告运营',
        'icon' => 'fa fa-fw fa-folder-open-o',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '广告管理',
            'icon' => 'fa fa-fw fa-list',
            'url_value' => 'operation/ads/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'operation/ads/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'operation/ads/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '启用',
                'icon' => '',
                'url_value' => 'operation/ads/enable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '禁用',
                'icon' => '',
                'url_value' => 'operation/ads/disable',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'operation/ads/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '广告位管理',
            'icon' => 'fa fa-fw fa-list',
            'url_value' => 'operation/ads_type/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'operation/ads_type/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'operation/ads_type/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'operation/ads_type/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '设置状态',
                'icon' => '',
                'url_value' => 'operation/ads_type/setstatus',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '导航管理',
        'icon' => 'fa fa-fw fa-fighter-jet',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '导航管理',
            'icon' => 'fa fa-fw fa-fighter-jet',
            'url_value' => 'operation/nav/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'operation/nav/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'operation/nav/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'operation/nav/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '设置状态',
                'icon' => '',
                'url_value' => 'operation/nav/setstatus',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
          [
            'title' => '导航位管理',
            'icon' => 'fa fa-fw fa-list',
            'url_value' => 'operation/nav_type/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'operation/nav_type/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'operation/nav_type/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'operation/nav_type/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '设置状态',
                'icon' => '',
                'url_value' => 'operation/nav_type/setstatus',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
      [
        'title' => '促销管理',
        'icon' => 'fa fa-fw fa-object-group',
        'url_value' => '',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 100,
        'status' => 1,
        'child' => [
          [
            'title' => '优惠券管理',
            'icon' => 'fa fa-fw fa-newspaper-o',
            'url_value' => 'operation/coupon/index',
            'url_target' => '_self',
            'online_hide' => 0,
            'sort' => 100,
            'status' => 1,
            'child' => [
              [
                'title' => '发放优惠券',
                'icon' => 'fa fa-fw fa-paper-plane-o',
                'url_value' => 'operation/coupon/send_coupon',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 99,
                'status' => 1,
              ],
              [
                'title' => '优惠券领取记录',
                'icon' => '',
                'url_value' => 'operation/coupon/receiving',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '新增',
                'icon' => '',
                'url_value' => 'operation/coupon/add',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '编辑',
                'icon' => '',
                'url_value' => 'operation/coupon/edit',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '删除',
                'icon' => '',
                'url_value' => 'operation/coupon/delete',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
              [
                'title' => '设置状态',
                'icon' => '',
                'url_value' => 'operation/coupon/setstatus',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 100,
                'status' => 1,
              ],
            ],
          ],
        ],
      ],
    ],
  ],
];
